### ISSUE TITLE
Where to get EPM240T100I5N?

### ISSUE THREAD

**Issue by tyristori** [captain-amygdala/pistorm#24]
This part is hard to get currently. LCSC, Mouser or DigiKey doesn't have it on stock.

**Comment by abrugsch** [comment]
Correct. It's out of stock almost everywhere and most places that do have it are on Ali Express where the vendors are mostly admitting they have fakes.
At present, alternative variants that are usable are EPM240T100*
C5N
I5N
A5N
C5
I5
A5

**NOT** yet tested are any **GT** models (but hopefully they will be as there is more availability of them)
Also MAX V chips are due to be tested
