### ISSUE TITLE
¿how difficult would be to make a PiStormG5 to replace 970 CPUs in G5 PowerMacs 2003-2005 ?

### ISSUE THREAD

**Issue by juanpc2018** [captain-amygdala/pistorm#63]
New A-EON X5000 P5020 / P5040 are too much $$, and BTO. $2500usd.
a New Raptor Talos II / Lite or Bird are POWER9 but Unknown if AmigaOS4.1 works, 
and is a lot more $$$.

There are PowerMac G5 doing Nothing, 
because are slow, power inneficient 90nm CPUs, & dont have drivers for faster GPUs or NVMe.
except QUAD G5, "Dual Dual Core CPUs", most are Damaged by Liquid Cooling leak and other problems.

some people found the source code for OSX PPC, and optimized as much as possible,
there is a 200% increase in performance 
Official OSX Leopard 10.5.8 vs. Unofficial OSX Sobet 10.5.9

MorphOS is based on AROS, and AROS is based on AmigaOS3 for 68k CPUs,
but MorphOS is for PowerPC, and its also very optimized "can play youtube".
but that Not enough...

X5000 is Not CHRP compliant, 
has U-Boot, instead of OpenFirmware like PowerMacs "AIM alliance invented PowerPC"...
CHRP .pdfs are 1000 pages to Boot a machine,
havent searched the Schematics for the PowerMc G5

Anyway...
AmigaOS4.1 and MorphOS sold for Download in their websites,
are for PowerPC but... 
Hyperion Entertainment AmigaOS4.1 sells the "Classic Final Edition", 
that only works in Emulators and Cybarstorm PPC 604e CPU.
there are other ISO installers when purchasing a New X5000, X1000, AmigaONE 500, Pegasos 1 & 2 "Discontinued",

The Problem with PPC is that is Not CHRP compliant, its a mess, 
requires different installer ISO for each CPU / Machine type...
There is something wrong with PPC.

example: Fienix blogspot
has 3x isos:
1x for X1000, 
1x for X5000 and Nec PCIe, 
1x for Sam460 CPUs, Pegasos, PPC Emulators. "Classic"

Most other Linux distros with PPC have 2x PPC versions.

a PiStormG5 for PowerMac G5 and G4 would solve 
most problems...
maybe AmigaOS4.1 FE Classic could be installed and Run Faster,
without PPC emulator.
OSX Sobet, posibilities are endless. 

Problem is the CPU:
G5 970 CPUs are 64-Bit, but most OSX PPC software was Not G5 optimized, 
only Cinebench 2003 i know had G4, G5 & Windows versions.
G4 is 32-Bit.

Odroid N2+ seems to be the fastest ARM SBC.

Emulating the PPC CPU with FPGA is another option,
or a daughter board to plug-in a Real P5020 / P5040 CPUs
to replace the old 970 CPUs that are basically useless.

PowerMac G5 failed for many reasons...
Has a Hardware Bug in PowerSaving.
does Not have ECC Memory, 
the reason why ViginiaTech Super Computer G5 Cluseter was a failure...

most people today remove the board and install a PC board.

**Comment by gianlucarenzi** [comment]
may be I can clarify what a PiStorm is and what is not. PiStorm (powered by an moderate ARM64 SoC running under the 2Ghz speed) is acting like a soft core processor using the same bus architecture of a 16 bit m68k and now the 32 bit m68k. hardware wise it is seen like a real microprocessor in the middle of the bus, and some stuff are running in the ARM side only (fastmem and RTG for example). it is very hard to obtain the same results using a 64 bit superscalar processor like mP750 g4 or G5. this is a very complex design and if somebody is trying to run over a raspberry pi a PowerPC emulator is facing a lot of performances issues for sure. and these issues are on the emulating the cores, bus, and so forth. maybe a fast and complex FPGA (instead of a fairly simple cpld) a lot of processing power like a multicolores Intel or AMD processor threads should be a better choice. but with all that power why emulate an old processor architecture? only for using morph OS, AROS or Amiga? they surely run faster in emulated mode like qemu or WinUAE or Amyberry.
